name: collapsible
description: A widget that implicitly collapses and expands around its child by clipping it.
version: 1.0.0
homepage: https://github.com/james-alex/collapsible

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
